//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmManager
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Director
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Director()
        {
            this.Movies = new HashSet<Movie>();
        }
    
        public int IDDirector { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Max length 50")]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Max length 50")]
        public string LastName { get; set; }
        [Required]        
        public int Age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Movies { get; set; }

        public override string ToString()
        {
            return $"{FirstName} {LastName}"; 
        }
    }
}
